name: Publish Nuget

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: set artifacts directory env
        run: echo "ARTIFACTS_DIRECTORY=artifacts" >> $GITHUB_ENV
      - name: set env var
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Build
        run: dotnet build
      - name: Package project
        run: |
          dotnet pack --configuration Release /p:Version=${{env.RELEASE_VERSION}} -o ${{env.ARTIFACTS_DIRECTORY}}
      - name: Publish project
        env:
          PACKAGE_PATH: ${{env.ARTIFACTS_DIRECTORY}}/Hackney.HousingRepairsOnline.Authentication.${{env.RELEASE_VERSION}}.nupkg
        run: |
          echo $PWD
          dotnet nuget push $PACKAGE_PATH --api-key ${{secrets.TOKEN}} --source https://nuget.pkg.github.com/LBHackney-IT/index.json
